Send expected cloudPlatform with DRS requests
microsoft/ga4gh-tes pull request #708
Opened 2024-05-14 19:32 UTC by jgainerdewar

DRSHub was receiving `cloudPlatform: Azure` rather than `cloudPlatform: azure` as expected. I tried to do this in a less gross way, but it looks like support for varying enum names and JSON serialized values is not great with this library: https://github.com/dotnet/runtime/issues/74385 Happy for alternate recommendations.

2024-05-14 19:41 UTC, jgainerdewar commented
@microsoft-github-policy-service agree [company="Broad Institute"]

2024-05-14 19:44 UTC, BMurri approved these changes

2024-05-14 19:44 UTC, jgainerdewar commented
@ agree company="Broad Institute"

2024-05-14 20:31 UTC, BMurri commented
I'm making a suggestion that I will include as a PR to this PR. Expect it later today.

2024-05-14 21:02 UTC, BMurri commented
@jgainerdewar here are my proposed changes: jgainerdewar/ga4gh-tes#1

2024-05-14 21:03 UTC, BMurri commented
Also, I think you need to reinsert `microsoft-github-policy-service ` between the `@` and the `agree...`

2024-05-14 21:04 UTC, BMurri requested changes
I provided a PR to your PR. Please consider those changes.

2024-05-15 13:03 UTC, jgainerdewar commented
@microsoft-github-policy-service agree company="Broad Institute"

2024-05-15 13:13 UTC, jgainerdewar commented
Thanks @BMurri, this is much better! I've retested the new changes and confirmed it still works as expected.

2024-05-15 15:44 UTC, BMurri approved these changes

2024-05-15 16:45 UTC, merged